# 行列演算の基礎

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- ベクトルの定義
- 行例の定義
- 転置
- 逆行列
- 行列積

In [10]:
import numpy as np

In [11]:
# ベクトルの定義
x = np.array([[1], [2], [3]])
print(x)

[[1]
 [2]
 [3]]


In [12]:
# 行列の定義
X = np.array([[1, 2], [3, 4]])
print(X)

[[1 2]
 [3 4]]


In [13]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [14]:
# 逆行列
# linear algebra: 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [15]:
# 行列積
XX_inv = np.dot(X, X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


# よくある間違い

In [16]:
x = np.array([1, 2, 3])

In [17]:
x.T

array([1, 2, 3])

In [18]:
x = np.array([[1, 2, 3]])
x.T

array([[1],
       [2],
       [3]])

# Numpyでよく使う処理

In [19]:
X = np.array([
    [2, 3, 4],
    [1, 2, 3]
])

In [20]:
row, col = X.shape

In [21]:
print(row, col)

2 3


In [22]:
for x in X:
    print(x)
    print('--')

[2 3 4]
--
[1 2 3]
--


# 演習問題

$\boldsymbol{X} = \begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 5 \\
1 & 2 & 4 \\
1 & 5 & 9 \\
\end{bmatrix}
,\ \boldsymbol{y} = \begin{bmatrix}
1 \\
5 \\
6 \\
8 \\
\end{bmatrix}
$のとき

$\boldsymbol{w} = (\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [23]:
# Xの定義
X = np.array([
    [1, 2, 3],
    [1, 2, 5],
    [1, 3, 4],
    [1, 5, 9]
])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [24]:
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
print(y)

[[1]
 [5]
 [6]
 [8]]


In [25]:
# Step 1
XtX = np.dot(X.T, X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [26]:
# Step 2
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [27]:
# Step 3
Xty = np.dot(X.T, y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [28]:
# Step 4
w = np.dot(XtX_inv, Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnでの実装

In [29]:
import sklearn

In [30]:
# 重回帰分析の読み込み

In [31]:
from sklearn.linear_model import LinearRegression

In [36]:
# モデルの宣言
model = LinearRegression(fit_intercept=False)

In [37]:
# モデルの学習　パラメータの調整
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=False)

In [38]:
# 調整後のパラメータ
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [39]:
model.intercept_

0.0

In [43]:
# 予測精度　決定件数
model.score(X, y)

0.6923076923076923

In [44]:
# 予測値の計算
x = np.array([
    [1, 2, 3]
])

In [47]:
y_pred = model.predict(x)
y_pred

array([[3.]])