In [12]:
import numpy as np

In [13]:
my_list = [1, 2, 3]

In [14]:
arr = np.array(my_list)

In [15]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0, 11, 10)

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [24]:
np.random.randint(0, 10, (3, 3))

array([[1, 1, 3],
       [8, 0, 9],
       [0, 5, 9]])

In [30]:
np.random.seed(1)
arr = np.random.randint(0, 10, 10)

In [31]:
arr.mean()

5.0

In [32]:
arr.max()

9

In [33]:
arr.min()

0

In [34]:
arr.argmax()

2

In [35]:
arr.reshape(2, 5)

array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9]])

In [36]:
mat = np.arange(0, 100).reshape(10, 10)

In [37]:
mat[:, 0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [39]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [40]:
my_filter = mat > 50

In [41]:
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])