In [12]:
import numpy as np

In [13]:
my_list = [1, 2, 3]

In [14]:
arr = np.array(my_list)

In [15]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])