In [12]:
import numpy as np

In [13]:
my_list = [1, 2, 3]

In [14]:
arr = np.array(my_list)

In [15]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [18]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0, 11, 10)

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [24]:
np.random.randint(0, 10, (3, 3))

array([[1, 1, 3],
       [8, 0, 9],
       [0, 5, 9]])

In [30]:
np.random.seed(1)
arr = np.random.randint(0, 10, 10)

In [31]:
arr.mean()

5.0

In [32]:
arr.max()

9

In [33]:
arr.min()

0

In [34]:
arr.argmax()

2

In [35]:
arr.reshape(2, 5)

array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9]])

In [36]:
mat = np.arange(0, 100).reshape(10, 10)

In [37]:
mat[:, 0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [39]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [40]:
my_filter = mat > 50

In [41]:
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# NumPy実践メソッド

In [1]:
import numpy as np
sample_data = np.arange(10)
print(np.sqrt(sample_data))
print(np.exp(sample_data))
# 平均や最大値等の計算ができます。axisで行か列の指定が可能です。
# 統計関数
sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)
print("平均:",sample_multi_array_data1.mean())
print("最大値:",sample_multi_array_data1.max())
print("合計:",sample_multi_array_data1.sum())
# 行列の指定
print("行の合計:",sample_multi_array_data1.sum(axis=1))
print("列の合計:",sample_multi_array_data1.sum(axis=0))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
平均: 4.0
最大値: 8
合計: 36
行の合計: [ 3 12 21]
列の合計: [ 9 12 15]


In [2]:
import numpy as np
a = np.random.randint(6, size=(2,3))

"""
array([[2, 0, 5],
       [2, 2, 4]])
"""

np.any(a==6) # aの要素に、6が1つでもあるかどうか
"""
上記の場合、6が無いので、Falseが返ります。
"""

# keepdimsをTrueにすると次のような出力を得られます。
d = np.any(a==2, keepdims=True)

"""
出力

array([[ True]], dtype=bool)
"""

'\n出力\n\narray([[ True]], dtype=bool)\n'

In [3]:
import numpy as np
a = np.array([0,1,1])
b = np.array([1,1,1])

print(np.all(a)) # False
print(np.all(b)) # True

c = np.array([
    [0,0,1],
    [1,1,2],
    [0,1,2]
])

# axis=0で行方向
d = np.all(c, axis=0) # array([False, False,  True], dtype=bool)

# axis=1で列方向
d2 = np.all(c, axis=1) # array([False,  True, False], dtype=bool)

False
True


In [4]:
import numpy as np
np.random.rand() # 0〜1の乱数を1個生成

token = np.random.rand(100) # 0〜1の乱数を100個生成
print(token)
token2 = np.random.rand(10,10) # 0〜1の乱数で 10x10 の行列を生成
print(token2)
token3 = np.random.rand(100) * 40 + 30 # 30〜70の乱数を100個生成
print(token3)

[0.37108103 0.12015766 0.71734931 0.32184101 0.83806779 0.9760542
 0.78981477 0.79542414 0.41795176 0.26138042 0.09337942 0.63359054
 0.23003905 0.25799132 0.43853268 0.58834255 0.02761431 0.41525999
 0.70930303 0.59684312 0.48754917 0.86814216 0.42788014 0.08475868
 0.71427215 0.97708017 0.11152724 0.59722556 0.37831222 0.88259466
 0.02540214 0.68900162 0.63601646 0.57873091 0.87342785 0.1318112
 0.44241652 0.76451581 0.87455188 0.54615321 0.25117806 0.78988955
 0.53133609 0.26299786 0.35945925 0.82926447 0.79906006 0.69416933
 0.19625887 0.85976507 0.39612428 0.44473754 0.16615665 0.9781931
 0.249303   0.72881326 0.928079   0.83128948 0.44443139 0.79875564
 0.82697047 0.42071877 0.06730816 0.66741577 0.53001065 0.3904467
 0.64327321 0.90693834 0.08504242 0.87940435 0.17289279 0.72879183
 0.22512383 0.72857718 0.39173697 0.55789329 0.12589464 0.89309662
 0.92065985 0.67607266 0.04544539 0.88097808 0.70690858 0.3925875
 0.16168283 0.78415217 0.84861968 0.05242838 0.17339849 0.14088567


In [5]:
import numpy as np
"""
標準正規分布。
いわゆるガウシアン。
標準正規分布ならば randn() で、
平均・分散を指定したい場合は normal() を用います。"""
np.random.randn() # 標準正規分布 (平均0, 標準偏差1)
np.random.randn(10) # 標準正規分布を10個生成
np.random.randn(10,10) # 標準正規分布による 10x10 の行列
np.random.normal(50,10) # 平均50、標準偏差10の正規分布

""" 二項分布"""
np.random.binomial(n=100, p=0.5)

""" ポアソン分布。
稀にしか起きない現象を長時間観測したときに起きる回数の分布。
λはその平均。
"""
np.random.poisson(lam=10)     # λ=10 のポアソン分布

""" ベータ分布。二項分布の共役事前分布などに用いる。"""
np.random.beta(a=3, b=5)      # a=3, b=5 のベータ分布

0.7098807045348083

In [7]:
import numpy as np
np.random.randint(100) #  0〜99 の整数を1個生成
np.random.randint(30,70) # 30〜69 の整数を1個生成
np.random.randint(0,100,20) #  0〜99 の整数を20個生成
np.random.randint(0,100,(5,5)) #  0〜99 の整数で5x5の行列を生成

np.random.random_integers(100) # 1〜100 の整数を1個生成
np.random.random_integers(30,70) # 30〜70 の整数を1個生成

"""
Numpyで生成される乱数は擬似乱数であるため、
固定したseedを指定してやれば毎回同じ乱数が出ます。
デバッグ時など毎回同じ乱数を出して欲しいときに使います。
"""

np.random.seed(0) # 数値はなんでもOK
np.random.rand() # 毎回同じ値を返します。

C:\Users\haruk\Anaconda3\envs\ai-gpu\Lib\site-packages\ipykernel_launcher.py:7: DeprecationWarning: This function is deprecated. Please call randint(1, 100 + 1) instead
  import sys
C:\Users\haruk\Anaconda3\envs\ai-gpu\Lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: This function is deprecated. Please call randint(30, 70 + 1) instead
  


0.5488135039273248

In [8]:
import numpy as  np
x = np.arange(10)
array_copy = np.copy(x)

In [9]:
import numpy as  np
zero_array = np.zeros(10) #[0,0,0,0,0,0,0,0,0,0]

In [10]:
import numpy as np

data = np.linspace(0, 100, 10)
print(data)

"""
[   0.           11.11111111   22.22222222   33.33333333   44.44444444
   55.55555556   66.66666667   77.77777778   88.88888889  100.        ]
"""
# endpointにFalseの時
data2 = np.linspace(0, 100, 10, endpoint=False)
print(data2)

"""
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90.]
"""

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


'\n[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90.]\n'

In [11]:
import numpy as np
data1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
data2 = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

# vstackは配列を縦に連結
print(np.vstack((data1, data2)))

"""
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
"""

# hstackは配列を横に連結
print(np.hstack((data1, data2)))

"""
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
"""

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


'\n[[ 1  2  3 11 12 13]\n [ 4  5  6 14 15 16]\n [ 7  8  9 17 18 19]]\n'

In [12]:
import numpy as np
names = np.array(['a','b','c','d','a'])
data = np.random.randn(5,5)

t = names == "a" #[True,False,False,False,True]

print(data)
print(data[t]) # 0番目と4番目の値が出力される
print(t) # [ True False False False  True]

[[ 0.74159174  1.55291372 -2.2683282   1.33354538 -0.84272405]
 [ 1.96992445  1.26611853 -0.50587654  2.54520078  1.08081191]
 [ 0.48431215  0.57914048 -0.18158257  1.41020463 -0.37447169]
 [ 0.27519832 -0.96075461  0.37692697  0.03343893  0.68056724]
 [-1.56349669 -0.56669762 -0.24214951  1.51439128 -0.3330574 ]]
[[ 0.74159174  1.55291372 -2.2683282   1.33354538 -0.84272405]
 [-1.56349669 -0.56669762 -0.24214951  1.51439128 -0.3330574 ]]
[ True False False False  True]
