# Tenforflow Syntax Basics

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.14.0


In [3]:
hello = tf.constant("Hello ")

In [4]:
world = tf.constant("World")

In [6]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [7]:
a = tf.constant(10)

In [8]:
b = tf.constant(20)

In [9]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [10]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [11]:
const = tf.constant(10)

In [12]:
fill_mat = tf.fill((4, 4), 10)

In [17]:
myzeros = tf.zeros((4, 4))

In [14]:
myones = tf.ones((4, 4))

In [15]:
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)

In [16]:
myrandu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [18]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [19]:
sess = tf.InteractiveSession()

In [21]:
for op in my_ops:
#     print(sess.run(op))
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.21786964 -0.80364823 -0.59683126  0.15025555]
 [-0.9100417  -1.541182   -0.26925838  1.1716506 ]
 [-0.22186759 -1.0248574  -0.9832949   1.6302937 ]
 [-0.8160541  -0.63935995  0.20346384 -0.7056174 ]]


[[0.13621259 0.750649   0.6034752  0.3408444 ]
 [0.5880798  0.08214414 0.6006615  0.42444265]
 [0.3177514  0.04716849 0.2874757  0.35247767]
 [0.09775329 0.34891045 0.43514204 0.87344956]]




In [23]:
a = tf.constant([[1, 2],
                 [3, 4]])

In [24]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [25]:
b = tf.constant([[10], [100]])

In [26]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [27]:
result = tf.matmul(a, b)

In [28]:
sess.run(result)

array([[210],
       [430]])

In [29]:
result.eval()

array([[210],
       [430]])