# Tenforflow Syntax Basics

In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

1.14.0


In [5]:
hello = tf.constant("Hello ")

In [6]:
world = tf.constant("World")

In [7]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [8]:
a = tf.constant(10)

In [9]:
b = tf.constant(20)

In [10]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [11]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [12]:
const = tf.constant(10)

In [13]:
fill_mat = tf.fill((4, 4), 10)

In [14]:
myzeros = tf.zeros((4, 4))

In [15]:
myones = tf.ones((4, 4))

In [16]:
myrandn = tf.random_normal((4, 4), mean=0, stddev=1.0)

In [17]:
myrandu = tf.random_uniform((4, 4), minval=0, maxval=1)

In [18]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [19]:
sess = tf.InteractiveSession()

In [20]:
for op in my_ops:
#     print(sess.run(op))
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.90605974  0.4058907  -0.2363351   0.2943049 ]
 [-1.4409807   0.87714946 -1.1709847  -0.779997  ]
 [-0.05264688 -0.20101638  0.15345144  0.13965687]
 [ 0.44485357  0.81274897 -0.86178356  0.7002848 ]]


[[0.30197704 0.04105771 0.08478391 0.08929408]
 [0.4232421  0.82439744 0.41293323 0.683864  ]
 [0.8990923  0.5397371  0.0990262  0.6259465 ]
 [0.465114   0.88351536 0.8831855  0.84125733]]




In [21]:
a = tf.constant([[1, 2],
                 [3, 4]])

In [22]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [23]:
b = tf.constant([[10], [100]])

In [24]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [25]:
result = tf.matmul(a, b)

In [26]:
sess.run(result)

array([[210],
       [430]])

In [27]:
result.eval()

array([[210],
       [430]])